drop schema public cascade;

drop table user if exists;
CREATE TABLE user (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name varchar(50),
last_name varchar(50),
pass varchar(50)
);

DROP TABLE follower IF EXISTS;
CREATE TABLE follower (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
follower_id integer NOT NULL,
followed_id integer NOT NULL,

FOREIGN KEY (follower_id) REFERENCES users(id),
FOREIGN KEY (followed_id) REFERENCES users(id)
);

DROP TABLE post IF EXISTS;
CREATE TABLE post (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id integer NOT NULL,
content varchar(250),
creation_date timestamp,
is_public boolean,

FOREIGN KEY (user_id) REFERENCES user(id)
);

