INSERT INTO "PUBLIC"."USERS" ("FIRST_NAME", "NICK_NAME", "LAST_NAME","EMAIL", "PASSWORD" ) VALUES ('Jan', 'jank', 'Kowalski', '123@GMAIL.COM','12345678');
INSERT INTO "PUBLIC"."USERS" ("FIRST_NAME", "NICK_NAME", "LAST_NAME","EMAIL", "PASSWORD" ) VALUES ('Piotr', 'piotrn', 'Nowak', '1234@GMAIL.COM', '12345678');
INSERT INTO "PUBLIC"."USERS" ("FIRST_NAME", "NICK_NAME", "LAST_NAME","EMAIL", "PASSWORD" ) VALUES ('Random', 'randomn', 'Name', '12345@GMAIL.COM','12345678');
INSERT INTO "PUBLIC"."USERS" ("FIRST_NAME", "NICK_NAME", "LAST_NAME","EMAIL", "PASSWORD" ) VALUES ('Popular', 'popularp', 'Person','123456@GMAIL.COM', '12345678');
INSERT INTO "PUBLIC"."USERS" ("FIRST_NAME", "NICK_NAME", "LAST_NAME","EMAIL", "PASSWORD" ) VALUES ('Stalker', 'stalkera', 'Alert', '1234567@GMAIL.COM','12345678');

INSERT INTO "PUBLIC"."POSTS" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (0, 'BLAHBLAHBLAHBLAH', '2022-11-12 12:49:36.00', true);
INSERT INTO "PUBLIC"."POSTS" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (1, 'BLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAH', '2022-11-12 12:49:36.00', true);
INSERT INTO "PUBLIC"."POSTS" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (2, 'BLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAH', '2022-11-12 12:49:36.00', true);
INSERT INTO "PUBLIC"."POSTS" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (3, 'BLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAH', '2022-11-12 12:49:36.00', true);
INSERT INTO "PUBLIC"."POSTS" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (4, 'BLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAH','2022-11-12 12:49:36.00', true);
INSERT INTO "PUBLIC"."POSTS" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (0, 'BLAHBL', '2022-11-12 12:49:36.00', false);

INSERT INTO "PUBLIC"."FOLLOWERS" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (0, 3);
INSERT INTO "PUBLIC"."FOLLOWERS" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (1, 3);
INSERT INTO "PUBLIC"."FOLLOWERS" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (2, 3);
INSERT INTO "PUBLIC"."FOLLOWERS" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (4, 3);
INSERT INTO "PUBLIC"."FOLLOWERS" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (4, 0);
INSERT INTO "PUBLIC"."FOLLOWERS" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (4, 1);
INSERT INTO "PUBLIC"."FOLLOWERS" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (4, 2);
