DROP SCHEMA public CASCADE;
DROP TABLE user IF EXISTS;
CREATE TABLE user (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name varchar(50),
nick_name varchar(50) NOT NULL,
last_name varchar(50) NOT NULL,
password varchar(50) NOT NULL
);

DROP TABLE post IF EXISTS;
CREATE TABLE post (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id integer NOT NULL,
content varchar(250),
creation_date timestamp,
is_public boolean,
FOREIGN KEY (user_id) REFERENCES user(id)
);

DROP TABLE follower IF EXISTS;
CREATE TABLE follower (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
follower_id integer NOT NULL,
followed_id integer NOT NULL,
FOREIGN KEY (follower_id) REFERENCES user(id),
FOREIGN KEY (followed_id) REFERENCES user(id)
);
