INSERT INTO "PUBLIC"."USER" ("FIRST_NAME", "NICK_NAME", "LAST_NAME", "PASSWORD" ) VALUES ('Jakub', 'jakops', 'yilmaz', '123456789');
INSERT INTO "PUBLIC"."USER" ("FIRST_NAME", "NICK_NAME", "LAST_NAME", "PASSWORD" ) VALUES ('jack', 'jacks', 'stan', '123456789');
INSERT INTO "PUBLIC"."USER" ("FIRST_NAME", "NICK_NAME", "LAST_NAME", "PASSWORD" ) VALUES ('dutch', 'randomn', 'Name', '12345679');
INSERT INTO "PUBLIC"."USER" ("FIRST_NAME", "NICK_NAME", "LAST_NAME", "PASSWORD" ) VALUES ('Arthur', 'morgan', 'Person', '123456789');
INSERT INTO "PUBLIC"."USER" ("FIRST_NAME", "NICK_NAME", "LAST_NAME", "PASSWORD" ) VALUES ('john', 'doe', 'temp', '123456789');

INSERT INTO "PUBLIC"."POST" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (0, 'sometext', '2022-11-12 12:00:00.00', true);
INSERT INTO "PUBLIC"."POST" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (1, 'sometextsometextsometexr', '2022-11-12 12:00:00.00', true);
INSERT INTO "PUBLIC"."POST" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (2, 'sometextsometextsometexrsometextsometextsometexr', '2022-11-12 12:00:00.00', true);
INSERT INTO "PUBLIC"."POST" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (3, 'sometextsometextsometexrsometextsometextsometexrsometextsometextsometexr', '2022-11-12 12:00:00.00', true);
INSERT INTO "PUBLIC"."POST" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (4, 'sometextsometextsometexrsometextsometextsometexrsometextsometextsometexrsometextsometextsometexr','2022-11-12 12:00:00.00', true);
INSERT INTO "PUBLIC"."POST" ("USER_ID", "CONTENT", "CREATION_DATE", "IS_PUBLIC" ) VALUES (0, 'textwrite', '2022-11-12 12:00:00.00', false);

INSERT INTO "PUBLIC"."FOLLOWER" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (0, 3);
INSERT INTO "PUBLIC"."FOLLOWER" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (1, 3);
INSERT INTO "PUBLIC"."FOLLOWER" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (2, 3);
INSERT INTO "PUBLIC"."FOLLOWER" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (4, 3);
INSERT INTO "PUBLIC"."FOLLOWER" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (4, 0);
INSERT INTO "PUBLIC"."FOLLOWER" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (4, 1);
INSERT INTO "PUBLIC"."FOLLOWER" ("FOLLOWER_ID", "FOLLOWED_ID") VALUES (4, 2);
