DROP SCHEMA public CASCADE;
DROP TABLE users IF EXISTS;
CREATE TABLE users (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name varchar(50),
last_name varchar(50) NOT NULL,
nickname varchar(50) NOT NULL,
password varchar(50) NOT NULL
);

DROP TABLE posts IF EXISTS;
CREATE TABLE posts (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id integer NOT NULL,
description varchar(250),
created_at timestamp,
is_public boolean,
FOREIGN KEY (user_id) REFERENCES users(id)
);

DROP TABLE followers IF EXISTS;
CREATE TABLE followers (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
follower_id integer NOT NULL,
followee_id integer NOT NULL,
FOREIGN KEY (follower_id) REFERENCES users(id),
FOREIGN KEY (followee_id) REFERENCES users(id)
);